name: learn-github-actions
on: [ push ]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '17.4.0'
      - run: npm install
      - run: npm lint
      - run: npm test